### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kazdyrkeicam** [kazdyrkeicam/PRNG_xorshift#1]
Generated package must contain:

- [ ] At least 1 num range of < 0x04 , 0x1D >
- [ ] At least 1 num range of < 0x1E , 0x27 >
- [ ] At least 1 num range of < 0x2D , 0x38 >
